### ISSUE TITLE
Why did we fork?

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/utf8_gatekeeper#3]
This appears to be a fork of [this repo](https://github.com/singlebrook/utf8-cleaner). Why did we fork, and can we merge back into the original project?

**Comment by lpil** [comment]
That one strips invalid chars, this one rejects those requests. I think this behaviour is better.

Probably didn't want to bother with building the behaviour picking config stuff.

**Comment by jonnyarnold** [comment]
Cool.
